---
title: "Revised Analysis of phenological shifts in Germany"
output: html_notebook
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(fig.align = "center", echo = FALSE)

# disable dplyr::summarise() grouping message
# also disable stringsasfactors
options(dplyr.summarise.inform = FALSE,
        stringsAsFactors = FALSE)

library("data.table")
library("rgbif")
library("raster")

# tidyverse stuff last to avoid masking these functions
library("magrittr")
library("forcats")
library("stringr")
library("ggplot2")
library("tidyr")
library("dplyr")
library("tidyselect")

## Functions ----------------------------------------------

source("scripts/functions.R")

# Control variables -------------------------------------------------

## Script control -----------------------------------------

test_run         <- FALSE

# run script for retrieving climate data from DWD regardless of data being 
# already present?
force.clim.get   <- FALSE

# run script for retrieving plant trait data from bioFlor regardless of data 
# being already present?
force.traits.get <- FALSE

# force running of occurrence getting script
force.occ.get <- TRUE

# control which of the downloaded files to delede
#   - "all": delete both .zip files and extracted occ .txt files
#   - "zip": delete only .zip files, keep .txt
#   - "txt": delete only .txt files, keep .zip
#   - "non": keep all files in download folder
delete.occ.download <- "non"


## Path names ---------------------------------------------

if (!test_run) {
  dat_occ_file   <- "data/occurrences_full_pruned_clim_elev.csv"
  dat_slope_year_file <- "data/rnd_eff_year.csv"
  dat_slope_temp_file <- "data/rnd_eff_temp.csv"
} else {
  dat_occ_file   <- "data/f_occurrences_full_pruned_elev_test.csv"
  dat_slope_year_file <- "data/rnd_eff_year_test.csv"
  dat_slope_temp_file <- "data/rnd_eff_temp_test.csv"
}

## Set graphics parameters --------------------------------

# set colour for raw data points
col.pt <- "gray31"

# set colour for static lines
col.line <- "gray31"

# set colour for axis elements
col.ax <- "gray31"

# set col for annotations
col.note <- "gray31"

# annotation text size
annot_text <- 20

# line types
lty.sec <- 3

# line size
hline_size_large <- 2
line_size_large <- 2.5

# text size
text_size_large <- 50
legend_text_size_large <- 40

# axis parameters
axis_size_large <- 2
axis_ticks_size_large <- 2
axis_ticks_length_large <- 16

# size of plot labels for cowplot
# when plots were optimized for 22 x 14 in
label_size <- 50

## define custom plotting theme ---------------------------

theme_shifts <- function (...) {
  
  theme_minimal() %+replace%
    
    theme(panel.grid = element_blank(),
          ...)
}

## define trivial group names -----------------------------

# set groups to be excluded
excl.group.year <- c("Diptera", "Hymenoptera")

# set named vector for recoding group names to common names
recode.vec <- c(
  "Coleoptera" = "Beetles",
  "Diptera" = "Flies",
  "Hymenoptera" = "Bees",
  "Lepidoptera" = "Butterflies/\nMoths"
)

# make alternative vector for interactions
recode.vec.int <- recode.vec[2:4]
recode.vec.int[1:3] <- c("Hoverfly - Plant", "Bee - Plant", "Butterfly - Plant")

# translate to trivial names
excl.trivial.year <- recode_factor(excl.group.year, !!! recode.vec)

### set colour tables -------------------------------------------------------

# define colours
# DO NOT CHANGE ORDER, only append
col.grp <-
  data.frame(
    group = c(
      "Beetles",
      "Flies",
      "Bees",
      "Butterflies/\nMoths",
      "Insects overall",
      "Plants",
      "Hoverfly - Plant",
      "Bee - Plant",
      "Butterfly - Plant",
      "Overall",
      "Insect dependent",
      "Intermediate",
      "Insect independent"
    ),
    colour = c(
      "#9815db",
      "#f41d0f",
      "#ffa500",
      "#4744ff",
      "gold",
      "#008a00",
      "#f41d0f",
      "#ffa500",
      "#4744ff",
      "deepskyblue",
      "red",
      "#ffa500",
      "#008a00"
    )
  )

# alternative: named vector
col.grp.vec <- col.grp$colour
names(col.grp.vec) <- col.grp$group

#set colours for Plant-Pollinator comparisons
col.plapoll <- col.grp[5:6,]

# static polls group (no exclusion)
col.poll.stc <- col.grp[1:4,]

#only for polls
col.poll <- col.grp[1:4,] %>% 
  filter(!(group %in% excl.trivial.year))

#only for plants
col.plant <- col.grp[6,]

#set colours for group comparisons (add plant group at the end)
col.group.stc <- bind_rows(col.poll.stc, col.plant)
col.group <- bind_rows(col.poll, col.plant)

#set colours for group comparisons including overall
col.group2.stc <- bind_rows(col.poll.stc, col.plapoll)
col.group2 <- bind_rows(col.poll, col.plapoll)

#set colours for PollDep comparisons
col.PollDep <- col.grp[11:13,]

# interaction colours with standard names
col.int.stc <- col.grp[7:9,]
col.int.stc$group <- c("Hoverfly", "Bee", "Butterfly")

#set colours for Interaction comparisions
col.int <- col.grp[7:9,]

#set colours for Interaction comparison with overall group
col.int2 <- col.grp[7:10,]

#set colours for Interaction group comparisions
col.int3 <- bind_rows(col.int, col.plant)

#set colours for decade comparisons
col.dec <- data.frame(group = c("1990s and before", "all decades", "1990s on"),
                      colour = c("#2F5496", "#972A4B", "#FF0000")
)

# colours for id.grps with scientific scheme
# TODO: Apply colour scheme throughout notebook
col.group.sci <- col.grp$colour[c(1:4, 6)]
names(col.group.sci) <- c("Coleoptera", "Diptera", "Hymenoptera", "Lepidoptera",
                          "Plants")

# Save options and parameters -----------------------------

# done so that reloading an older workspace does not overwrite changes to
# parameters, options and loaded functions
save.image('data/curr_environment.RData')

```



```{r Ensure additional data is present}

# Climate data --------------------------------------------

if (all(file.exists('static_data/overall_mean_temperature.csv',
                    'static_data/decadal_mean_temperature.csv'))) {
  run.clim.get <- FALSE
} else {
  run.clim.get <- TRUE
}

if (run.clim.get | force.clim.get) {
  source('scripts/get_german_climate_data.R')
}

# Plant trait data ----------------------------------------

if (file.exists('static_data/bioflor_traits.csv')) {
  run.traits.get <- FALSE
} else {
  run.traits.get <- TRUE
}

if (run.traits.get | force.traits.get) {
  source('scripts/get_bioflor_traits.R')
}

```



```{r get_occurrence_data, include=FALSE}

# for now, only check whether data and random effects are present
if (!any(file.exists(dat_occ_file)) || 
    force.occ.get) {
  source("scripts/get_occ_data_all_in_one.R")
}

if (!any(file.exists(dat_slope_temp_file, dat_slope_year_file))) {
  source("scripts/run_models.R")
}

```



```{r load_occurrence_slope_data}

# load plant trait data
plant_traits <- fread("static_data/bioflor_traits.csv") %>% 
  
  # prune out some unecessary data
  select(-all_of(c("AccName", "GbifKey", "OrigName", "bioflor_id")))

# load occurrence data
dat.occ <- fread(dat_occ_file, showProgress = FALSE) %>% 
  
  # add trait data
  left_join(plant_traits, by = "species") %>%
  
  # recode id.grp to use trivial names 
  # (recode only takes name/value pairs, so !!! expansion necessary)
  mutate(id.grp = recode_factor(id.grp, !!! recode.vec))


# load slope data
slopes_temp <- fread(dat_slope_temp_file)
slopes_year <- fread(dat_slope_year_file)


# add taxonomic and trait data to slopes
col_vec <- c("kingdom",
             "phylum",
             "id.grp",
             "order",
             "family",
             "genus",
             "species")

tax_df <- dat.occ %>%  
  select(all_of(col_vec)) %>% 
  distinct()
  

slopes_temp <- slopes_temp %>% 
  
  # add taxonomic data
  left_join(tax_df, by = "species") %>% 
  
  # add trait data
  left_join(plant_traits, by = "species")


slopes_year <- slopes_year %>%  
  
  # add taxonomic data
  left_join(tax_df, by = "species") %>% 
  
  # add trait data
  left_join(plant_traits, by = "species")


# generate df giving slopes for both vars
slopes_all <- left_join(slopes_temp,
                        slopes_year,
                        by = c("kingdom",
                               "phylum",
                               "id.grp",
                               "order",
                               "family",
                               "genus",
                               names(plant_traits)),
                        suffix = c("_temp", "_year")) %>% 
  
  # drop redundant cols
  select(-starts_with(c("group_",
                        "main_var_")))

```

## Summary of Shifts

```{r summarize_slopes}

slopes_temp_sum <- slopes_temp %>% 
  group_by(id.grp) %>% 
  summarise(n_spec              = length(slope),
            slope_mean          = mean(slope),
            slope_sd            = sd(slope),
            slope_se            = sd(slope) / sqrt(length(slope)),
            slope_ci_min        = ci.min(slope),
            slope_ci_max        = ci.max(slope),
            slope_frac_negative = sum(slope < 0) / length(slope),
            var                 = "Temperature")

slopes_year_sum <- slopes_year %>% 
  group_by(id.grp) %>% 
  summarise(n_spec              = length(slope),
            slope_mean          = mean(slope),
            slope_sd            = sd(slope),
            slope_se            = sd(slope) / sqrt(length(slope)),
            slope_ci_min        = ci.min(slope),
            slope_ci_max        = ci.max(slope),
            slope_frac_negative = sum(slope < 0) / length(slope),
            var                 = "Year")

#combine both summary data sets and display them
slopes_all_sum <- left_join(slopes_temp_sum,
                            slopes_year_sum,
                            by = c("id.grp"),
                            suffix = c("_temp",
                                       "_year")) %>% 
  
  # drop redundant columns
  select(-starts_with("var_"))

slopes_all_sum

```



```{r plot_slopes_vs_species_forest}

slopes_temp %>% 
  
  # plot slopes in ascending order
  ggplot(aes(reorder(species,  -slope), slope, col = id.grp)) +
  geom_point() +
  
  # clearly denote the 0 line
  geom_hline(yintercept = 0) +
  
  # invert x and y axis for classic forest plot look
  coord_flip() + 
  
  # break plot into facets, each with an independent species axis
  facet_wrap( ~ id.grp, scale = "free_y") +
  
  # add lables
  labs(title = "Shifts with temperature",
       y = "Slope",
       x = "Species") +
  
  # add coloring
  scale_color_manual(name   = "Group",
                     values = col.grp.vec) +
  
  # remove labeling of individual species (too much information at once)
  theme_shifts(axis.text.y  = element_blank(),
               axis.ticks.y = element_blank())


slopes_year %>% 
  
  # plot slopes in ascending order
  ggplot(aes(reorder(species,  -slope), slope, col = id.grp)) +
  geom_point() +
  
  # clearly denote the 0 line
  geom_hline(yintercept = 0) +
  
  # invert x and y axis for classic forest plot look
  coord_flip() + 
  
  # break plot into facets, each with an independent species axis
  facet_wrap( ~ id.grp, scale = "free_y") +
  
  # add lables
  labs(title = "Shifts with temperature",
       y = "Slope",
       x = "Species") +
  
  # add coloring
  scale_color_manual(name   = "Group",
                     values = col.grp.vec) +
  
  # remove labeling of individual species (too much information at once)
  theme_shifts(axis.text.y  = element_blank(),
               axis.ticks.y = element_blank())

```

## Analysis of differences between groups

```{r analyse_between_group_diffs}

cat("Differences in slope with temperature:\n\n")

aov_temp <- aov(data = slopes_temp, slope ~ id.grp)
summary(aov_temp)

cat("\n Pairwise differences: \n")

TukeyHSD(aov_temp)

cat("\n\n")
cat("----------------------------------------------------------\n\n")
cat("Differences in slope over time:\n\n")

aov_year <- aov(data = slopes_year, slope ~ id.grp)
summary(aov_year)

cat("\n Pairwise differences: \n")

TukeyHSD(aov_year)

```



```{r plot_slopes_vs_groups}

# for temp
ggplot() +
  
  # raw data
  geom_jitter   (data = slopes_temp,
                 aes(x = id.grp,
                     y = slope),
                 col = col.pt) +
  
  # error bars
  geom_errorbar (data = slopes_temp_sum,
                 aes(x    = id.grp,
                     ymin = slope_ci_min,
                     ymax = slope_ci_max,
                     col  = id.grp)) +
  
  # mean data
  geom_point    (data = slopes_temp_sum,
                 aes(x   = id.grp,
                     y   = slope_mean,
                     col = id.grp)) + 
  
  # line denoting 0
  geom_hline    (yintercept = 0,
                 col = col.line) +
  
  # add labels
  labs(title = "Between group differences in shift",
       subtitle = "with temperature",
       x = "Group",
       y = "Slope [days / \u00B0C] (\u00B1 95% CI)") +
  
  # add coloring
  scale_color_manual(name   = "Group",
                     values = col.grp.vec) +
  
  # suppress legend
  theme_shifts(legend.position = "none")



# for year
ggplot() +
  
  # raw data
  geom_jitter   (data = slopes_year,
                 aes(x = id.grp,
                     y = slope),
                 col = col.pt) +
  
  # error bars
  geom_errorbar (data = slopes_year_sum,
                 aes(x    = id.grp,
                     ymin = slope_ci_min,
                     ymax = slope_ci_max,
                     col  = id.grp)) +
  
  # mean data
  geom_point    (data = slopes_year_sum,
                 aes(x   = id.grp,
                     y   = slope_mean,
                     col = id.grp)) + 
  
  # line denoting 0
  geom_hline    (yintercept = 0,
                 col = col.line) +
  
  # add labels
  labs(title = "Between group differences in shift",
       subtitle = "over time",
       x = "Group",
       y = "Slope [days / year] (\u00B1 95% CI)") +
  
  # add coloring
  scale_color_manual(name   = "Group",
                     values = col.grp.vec) +
  
  # suppress legend
  theme_shifts(legend.position = "none")

```

## Analysis of correlation of time and temperature shifts

```{r analyse_year_temp_corr}

# perform correlation test of time and temp slopes for each group and
# store results in df
corr_slopes <- lapply(
  unique(slopes_all$id.grp),
  function(id.grp_var, data = slopes_all) {
    
    slopes_grp <- filter(data, id.grp == id.grp_var)
    
    # make sure data has enough observations for cor.test
    if (nrow(slopes_grp) > 2) {
      
      test <- cor.test(slopes_grp$slope_year,
                       slopes_grp$slope_temp)
      
      res <- data.frame(id.grp = id.grp_var,
                        cor    = test[["estimate"]][["cor"]],
                        t      = test[["statistic"]],
                        df     = test[["parameter"]][["df"]],
                        pval   = test[["p.value"]])
      
      return(res)
      
    } else {
      
      # if we have not enough observations, return the closest thing
      #   to NAs
      res <- data.frame(id.grp = id.grp_var,
                        cor    = NA,
                        t      = "-",
                        df     = "-",
                        pval   = NA)
      
      return(res)
      
    }
    
  })

# bind_rows was acting up, so do.call(rbind) it is
corr_slopes <- do.call(rbind, corr_slopes) %>%
  
  # format pvalues into significance symbols
  mutate(pval.sig = cut(
    pval,
    breaks = c(0, 0.001, 0.01, 0.05, 0.1, 1),
    labels = c("***", "**", "*", ".", " "),
    right  = FALSE )) %>%
  
  # special case of NAs
  mutate(pval.sig = str_replace_na(pval.sig, "-")) %>%
  
  # also add group sizes for plotting (slightly hacky)
  left_join(select(slopes_all_sum, id.grp, n_spec_temp), by = "id.grp")


```


```{r plot_year_vs_temp_slopes_correlation}

ggplot() +
  
  # add 0 lines
  geom_hline     (yintercept = 0, col = col.line) + 
  geom_vline     (xintercept = 0, col = col.line) +
  
  # add raw data
  geom_point     (data = slopes_all,
                  aes(x = slope_year,
                      y = slope_temp),
                  col = col.pt) + 
  
  # add year errorbar 
  geom_errorbarh (data = slopes_all_sum,
                  aes(y    = slope_mean_temp,
                      xmin = slope_ci_min_year,
                      xmax = slope_ci_max_year,
                      col  = id.grp
                      )) +
  
  # add temp errorbar
  geom_errorbar  (data = slopes_all_sum,
                  aes(x    = slope_mean_year,
                      ymin = slope_ci_min_temp,
                      ymax = slope_ci_max_temp,
                      col  = id.grp))  +
  
  # add group means
  geom_point     (data = slopes_all_sum,
                  aes(x    = slope_mean_year,
                      y    = slope_mean_temp,
                      col  = id.grp)) +
  
  # add group sizes, correlation coefficient and its significance
  geom_text      (data = corr_slopes,
                  
                  # set text at the middle of all time slopes and slightly 
                  #   above the max of all temp slopes
                  aes(x = mean(c(min(slopes_all$slope_year),
                                 max(slopes_all$slope_year))),
                      y = ypos(slopes_all$slope_temp),
                      
                      label = str_glue("n = {n_spec_temp}, ",
                                       "r = {round(cor, 2)}\n{pval.sig}")),
                  col = col.note) +
  
  # adjust ylim to fit text
  ylim(c(min(slopes_all$slope_temp), max(slopes_all$slope_temp) * 2)) +
  
  # split the plot based on the group
  facet_wrap( ~ id.grp) + 
  
  # improve axis lables 
  labs(x = "Shift over time",
       y = "Shift with temperature") +
  
  # add coloring
  scale_color_manual(name   = "Group",
                     values = col.grp.vec) +
  
  # disable the legend
  theme_shifts(legend.position = "none")

```

## Analysis of synchrony

```{r summarize_interactions}

#load interaction data
int_data <- read.csv(paste0("static_data/",
                           "plant_pollinator_interactions_for_potential_",
                           "networks_2018.csv")) %>%
  
  # make names less unwieldy
  rename(poll = POLLINATOR_NAME, plant = PLANT_NAME, group = Group) %>%
  
  # filter out species which have no occurrence data
  filter(
    plant %in% unique(dat.occ$species) &
    poll  %in% unique(dat.occ$species)
    ) %>% 
  
  #add the plant trait data to the interactions
  left_join(plant_traits,
            by = c("plant" = "species")) %>%
  
  #exclude interactions with pollinator independent plants
  filter(PollDep != "No") %>%
  
  #reorder factor levels for more intuitive plotting
  mutate(group = fct_relevel(group, "Hoverfly", "Bee", "Butterfly"))


# display numbers of unique plants and pollinators there are per group
int_data_sum <- int_data %>% 
  select(poll, plant, group) %>% 
  group_by(group) %>% 
  summarise(across(everything(), uniqueN))

int_data_sum

```


```{r compute_slope_interactions}

int_slope_syn <- int_data %>% 
  apply(1, function(int_data_row) {
    
    # get slope data for plant and poll
    slope_all_plant <- slopes_all %>% 
      filter(species == int_data_row["plant"])
    
    slope_all_poll  <- slopes_all %>% 
      filter(species == int_data_row["poll" ])
    
    # browser()
    
    return(data.frame(plant = int_data_row["plant"],
                      poll  = int_data_row["poll" ],
                      group = int_data_row["group"],
                      
                      slope_temp_plant = slope_all_plant$slope_temp,
                      slope_temp_poll  = slope_all_poll $slope_temp,
                      
                      slope_temp_diff  = slope_all_plant$slope_temp - 
                        slope_all_poll $slope_temp,
                      
                      
                      slope_year_plant = slope_all_plant$slope_year,
                      slope_year_poll  = slope_all_poll $slope_year,
                      
                      slope_year_diff  = slope_all_plant$slope_year - 
                        slope_all_poll $slope_year))
    
  }) %>% 
  
  bind_rows()

# head(int_slope_syn)

```



```{r analyse_between_group_diffs_int}

cat("Differences in interaction slope difference with temperature:\n\n")

aov_int_temp <- aov(data = int_slope_syn, slope_temp_diff ~ group)
summary(aov_int_temp)

cat("\n Pairwise differences: \n")

TukeyHSD(aov_int_temp)

cat("\n\n")
cat("----------------------------------------------------------\n\n")
cat("Differences in interaction slope difference over time:\n\n")

aov_int_year <- aov(data = int_slope_syn, slope_year_diff ~ group)
summary(aov_int_year)

cat("\n Pairwise differences: \n")

TukeyHSD(aov_int_year)

```



```{r summarize_slope_interactions}

int_slope_syn_sum <- int_slope_syn %>% 
  group_by(group) %>% 
  summarise(n_int                         = length(slope_temp_plant),
            
            # summarize temp diff
            slope_temp_diff_mean          = mean(slope_temp_diff),
            slope_temp_diff_sd            = sd(slope_temp_diff),
            slope_temp_diff_se            = sd(slope_temp_diff) / 
              sqrt(length(slope_temp_diff)),
            
            slope_temp_diff_ci_min        = ci.min(slope_temp_diff),
            slope_temp_diff_ci_max        = ci.max(slope_temp_diff),
            slope_temp_diff_frac_negative = sum(slope_temp_diff < 0) /
              length(slope_temp_diff),
            
            
            # summarize year diff
            slope_year_diff_mean          = mean(slope_year_diff),
            slope_year_diff_sd            = sd(slope_year_diff),
            slope_year_diff_se            = sd(slope_year_diff) / 
              sqrt(length(slope_year_diff)),
            
            slope_year_diff_ci_min        = ci.min(slope_year_diff),
            slope_year_diff_ci_max        = ci.max(slope_year_diff),
            slope_year_diff_frac_negative = sum(slope_year_diff < 0) /
              length(slope_year_diff)
  )

int_slope_syn_sum

```



```{r plot_slope_interactions}

# for temp
ggplot() +
  
  # raw data
  geom_jitter   (data = int_slope_syn,
                 aes(x = group,
                     y = slope_temp_diff),
                 col = col.pt) +
  
  # error bars
  geom_errorbar (data = int_slope_syn_sum,
                 aes(x    = group,
                     ymin = slope_temp_diff_ci_min,
                     ymax = slope_temp_diff_ci_max,
                     col  = group)) +
  
  # mean data
  geom_point    (data = int_slope_syn_sum,
                 aes(x   = group,
                     y   = slope_temp_diff_mean,
                     col = group)) + 
  
  # line denoting 0
  geom_hline    (yintercept = 0,
                 col = col.line) +
  
  # add labels
  labs(title = "Interaction shift differences",
       subtitle = "with temperature",
       x = "Group",
       y = "Slope difference [days / \u00B0C] (\u00B1 95% CI)") +
  
  # add color
  scale_color_manual(name   = "Group",
                     values = col.PollDep$colour) +
  
  # suppress legend
  theme_shifts(legend.position = "none")



# for year
ggplot() +
  
  # raw data
  geom_jitter   (data = int_slope_syn,
                 aes(x = group,
                     y = slope_year_diff),
                 col = col.pt) +
  
  # error bars
  geom_errorbar (data = int_slope_syn_sum,
                 aes(x    = group,
                     ymin = slope_year_diff_ci_min,
                     ymax = slope_year_diff_ci_max,
                     col  = group)) +
  
  # mean data
  geom_point    (data = int_slope_syn_sum,
                 aes(x   = group,
                     y   = slope_year_diff_mean,
                     col = group)) + 
  
  # line denoting 0
  geom_hline    (yintercept = 0,
                 col = col.line) +
  
  # add labels
  labs(title = "Interaction shift differences",
       subtitle = "over time",
       x = "Group",
       y = "Slope difference [days / year] (\u00B1 95% CI)") +
  
  # add color
  scale_color_manual(name   = "Group",
                     values = col.PollDep$colour) +
  
  # suppress legend
  theme_shifts(legend.position = "none")

```


## Analysis of influence of plant traits

```{r analyse_plant_traits_slope}

cat("Differences in slope with temperature between levels of pollinator ",
    "dependence:\n\n")

aov_int_temp <- aov(data = slopes_all, slope_temp ~ PollDep)
summary(aov_int_temp)

cat("\n Pairwise differences: \n")

TukeyHSD(aov_int_temp)

cat("\n\n")
cat("----------------------------------------------------------\n\n")
cat("Differences in in slope over time between levels of pollinator ",
    "dependence:\n\n")

aov_int_year <- aov(data = slopes_all, slope_year ~ PollDep)
summary(aov_int_year)

cat("\n Pairwise differences: \n")

TukeyHSD(aov_int_year)

```



```{r get_and_sum_plant_traits_slopes}

# filter out species without determined PollDep
#   (includes insects)
slopes_temp_polldep <- slopes_temp %>% 
  drop_na(PollDep)

slopes_year_polldep <- slopes_year %>% 
  drop_na(PollDep)

# summarise data sets
slopes_temp_polldep_sum <- slopes_temp_polldep %>% 
  group_by(PollDep) %>% 
  summarise(n_spec              = length(slope),
            slope_mean          = mean(slope),
            slope_sd            = sd(slope),
            slope_se            = sd(slope) / sqrt(length(slope)),
            slope_ci_min        = ci.min(slope),
            slope_ci_max        = ci.max(slope),
            slope_frac_negative = sum(slope < 0) / length(slope),
            var                 = "Temperature")

slopes_year_polldep_sum <- slopes_year_polldep %>% 
  group_by(PollDep) %>% 
  summarise(n_spec              = length(slope),
            slope_mean          = mean(slope),
            slope_sd            = sd(slope),
            slope_se            = sd(slope) / sqrt(length(slope)),
            slope_ci_min        = ci.min(slope),
            slope_ci_max        = ci.max(slope),
            slope_frac_negative = sum(slope < 0) / length(slope),
            var                 = "Year")

#combine both summary data sets and display them
slopes_all_polldep_sum <- left_join(slopes_temp_polldep_sum,
                                    slopes_year_polldep_sum,
                                    by = c("PollDep"),
                                    suffix = c("_temp",
                                               "_year")) %>% 
  
  # drop redundant columns
  select(-starts_with("var_"))

slopes_all_polldep_sum


```



```{r plot_plant_traits_slope}

# for temp
ggplot() +
  
  # raw data
  geom_jitter   (data = slopes_temp_polldep,
                 aes(x = PollDep,
                     y = slope),
                 col = col.pt) +
  
  # error bars
  geom_errorbar (data = slopes_temp_polldep_sum,
                 aes(x    = PollDep,
                     ymin = slope_ci_min,
                     ymax = slope_ci_max,
                     col  = PollDep)) +
  
  # mean data
  geom_point    (data = slopes_temp_polldep_sum,
                 aes(x   = PollDep,
                     y   = slope_mean,
                     col = PollDep)) + 
  
  # line denoting 0
  geom_hline    (yintercept = 0,
                 col = col.line) +
  
  # add labels
  labs(title = "Between group differences in shift",
       subtitle = "with temperature",
       x = "Group",
       y = "Slope [days / \u00B0C] (\u00B1 95% CI)") +
  
  # add coloring
  scale_color_manual(name = "Group",
                     labels = col.PollDep$group,
                     values = col.PollDep$colour) +
  
  # suppress legend
  theme_shifts(legend.position = "none")



# for year
ggplot() +
  
  # raw data
  geom_jitter   (data = slopes_year_polldep,
                 aes(x = PollDep,
                     y = slope),
                 col = col.pt) +
  
  # error bars
  geom_errorbar (data = slopes_year_polldep_sum,
                 aes(x    = PollDep,
                     ymin = slope_ci_min,
                     ymax = slope_ci_max,
                     col  = PollDep)) +
  
  # mean data
  geom_point    (data = slopes_year_polldep_sum,
                 aes(x   = PollDep,
                     y   = slope_mean,
                     col = PollDep)) + 
  
  # line denoting 0
  geom_hline    (yintercept = 0,
                 col = col.line) +
  
  # add labels
  labs(title = "Between group differences in shift",
       subtitle = "over time",
       x = "Group",
       y = "Slope [days / year] (\u00B1 95% CI)") +
  
  # add coloring
  scale_color_manual(name = "Group",
                     labels = col.PollDep$group,
                     values = col.PollDep$colour) +
  
  # suppress legend
  theme_shifts(legend.position = "none")

```